---
    version: "3.3"
    services:
      code-server:
        image: ghcr.io/linuxserver/code-server
        container_name: code-server
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - PASSWORD=password #optional
          - HASHED_PASSWORD= #optional
          - SUDO_PASSWORD=password #optional
          - SUDO_PASSWORD_HASH= #optional
          - PROXY_DOMAIN= #optional
        volumes:
        #   - ./:/home/coder/project
          - data:/home/coder/.local/share/code-server
        #   - /config:/config
        ports:
          - 8080:8080
        restart: unless-stopped
    volumes: 
        data: